version: '3.8'

services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
      - "8080:8080"
    environment:
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=0
      - LOCALSTACK_AUTH_TOKEN=ls-HUzOsiba-DUjA-1963-0518-juGUVOyA15b8
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volume:/var/lib/localstack"
  dynamodb-admin:
    container_name: "dynamodb-admin"
    image: aaronshaf/dynamodb-admin:latest
    ports:
      - "8001:8001"
    environment:
      - DYNAMO_ENDPOINT=http://localstack:4566
      - AWS_ACCESS_KEY_ID=local
      - AWS_SECRET_ACCESS_KEY=local
      - AWS_REGION=us-east-1
    depends_on:
      - localstack
