version: '3.8'

services:
  localstack:
    container_name: "localstack-main"
    image: localstack/localstack-pro:latest
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
      - "8080:8080"
    environment:
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=0
      - LOCALSTACK_AUTH_TOKEN=ls-HUzOsiba-DUjA-1963-0518-juGUVOyA15b8
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./volume:/var/lib/localstack"