apiVersion: v1
kind: Service
metadata:
  name: postgres-db
  namespace: 3-tier-app-eks
  labels:
    service: database
spec:
  type: ExternalName
  externalName: localhost.localstack.cloud
  ports:
  - port: 4511
  # postgres-db.devopsdozo.svc.cluster.local  
