apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
  namespace: 3-tier-app-eks
type: Opaque
data:
  DB_USERNAME: YWRtaW4K
  DB_PASSWORD: cGFzc3dvcmQK
  #SECRET_KEY: 
  DATABASE_URL: cG9zdGdyZXNxbDovL2FkbWluOnBhc3N3b3JkQHBvc3RncmVzLWRiLjMtdGllci1hcHAtZWtzLnN2Yy5jbHVzdGVyLmxvY2FsOjQ1MTEvdGVzdGRiCg==